name: figma-parser-frontend
services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: parser_frontend
    restart: always
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3000
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
