# Makefile for Figma Parser Frontend

start: ## Run frontend with Docker Compose
	cd docker && docker-compose up -d

start-logs: ## Run frontend with Docker Compose and show logs
	cd docker && docker-compose up

stop: ## Stop Docker containers
	cd docker && docker-compose down

restart: ## Restart Docker containers
	cd docker && docker-compose restart
