# Makefile for Figma Parser Backend Service

start: ## Run the application with Docker Compose
	cd docker && docker-compose up -d

stop: ## Stop Docker containers
	cd docker && docker-compose down

restart: ## Restart Docker containers
	cd docker && docker-compose restart

start-logs: ## Run the application with Docker Compose and show logs
	cd docker && docker-compose up	
