name: figma-parser-backend
services:
  db:
    image: postgres:15-alpine
    container_name: parser_db
    restart: always
    env_file:
      - docker_postgresql.env
    ports:
      - "5432:5432"
    expose:
      - '5432' # Opens port 5432 on the container
    volumes:
      - ./conf/pgsql.conf:/etc/postgresql/postgresql.conf # Where our db instance config is set
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 5s  
volumes:
  postgres_data: